apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-hpa
  labels:
    app: nginx
spec:
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: nginx
    namespace: test-hpa
    jsonPointers:
    - /spec/replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
  namespace: test-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageValue: 1
